Add/core tests instructions
woocommerce/woocommerce-e2e-boilerplate pull request #15
Opened 2021-07-21 16:02 UTC by zhongruige

This PR adds instructions on running the `@woocommerce/e2e-core-tests` to the README.

Closes https://github.com/woocommerce/woocommerce-e2e-boilerplate/issues/11

2021-07-22 13:23 UTC, rrennick requested changes
@zhongruige Can we add a link to the readme?  https://github.com/woocommerce/woocommerce/blob/trunk/tests/e2e/core-tests/README.md

2021-07-22 16:33 UTC, zhongruige commented
> @zhongruige Can we add a link to the readme? https://github.com/woocommerce/woocommerce/blob/trunk/tests/e2e/core-tests/README.md

Good call out @rrennick! I've added that here: https://github.com/woocommerce/woocommerce-e2e-boilerplate/pull/15/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R105

2021-08-04 19:07 UTC, rrennick approved these changes
@zhongruige This looks great.

2021-08-04 19:07 UTC, merged

2021-08-04 19:47 UTC, zhongruige commented
> @zhongruige This looks great.

Thank you for the review @rrennick!